
tasks:
  - init: ./gradlew build
  - init: chmod +x gradlew

vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - richardwillis.vscode-gradle
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-dependency
  
image:
  file: .gitpod.Dockerfile
