
tasks:
  - init: sdk install java
  - init: ./gradlew build
  - init: chmod +x gradlew
  - command: ./gradlew bootRun



vscode:
  extensions:
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-pack
    - richardwillis.vscode-gradle
    - redhat.java
    - vscjava.vscode-java-test
    - vscjava.vscode-java-dependency
